name: Create Cypress report
on:
  push:
    branches:
      - 'master'
  # Add this part if you want to schedule test rerun
  # schedule:
  #   - cron: '0 8 1-31 * *'

jobs:
  
  cypress-e2e-chrome81:
    name: Run on Chrome 81
    runs-on: ubuntu-18.04
    container: cypress/browsers:node12.16.2-chrome81-ff75
    steps:
      - uses: actions/checkout@v2
      
      - name: Install a project with a clean slate
        run: |
          npm ci
          $(npm bin)/cypress cache path
          $(npm bin)/cypress cache list
          $(npm bin)/cypress verify
      
      - name: Run Cypress tests
        run: npm test:chrome
        continue-on-error: true